[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "*.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/sitemap*.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "*.png"
  [headers.values]
    Content-Type = "image/png"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Content-Type = "image/jpeg"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Content-Type = "image/jpeg"

[[headers]]
  for = "*.gif"
  [headers.values]
    Content-Type = "image/gif"

[[headers]]
  for = "*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"

[[headers]]
  for = "*.ico"
  [headers.values]
    Content-Type = "image/x-icon"

[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Content-Type = "image/x-icon"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/favicon.png"
  [headers.values]
    Content-Type = "image/png"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.woff"
  [headers.values]
    Content-Type = "font/woff"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Content-Type = "font/woff2"

[[headers]]
  for = "*.ttf"
  [headers.values]
    Content-Type = "font/ttf"

[[headers]]
  for = "*.eot"
  [headers.values]
    Content-Type = "application/vnd.ms-fontobject"
